# Generated by Django 5.2.16 on 2026-07-24 07:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(db_comment='主键', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='最后更新时间')),
                ('project_no', models.CharField(db_comment='项目编号', max_length=32)),
                ('name', models.CharField(db_comment='项目名称', max_length=200)),
                ('project_type_code', models.CharField(db_comment='项目类型字典代码', max_length=64)),
                ('description', models.TextField(blank=True, db_comment='项目目标和范围说明')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('suspended', '已暂停'), ('completed', '已完成'), ('archived', '已归档')], db_comment='项目状态', default='draft', max_length=24)),
                ('planned_start_date', models.DateField(blank=True, db_comment='计划开始日期', null=True)),
                ('planned_end_date', models.DateField(blank=True, db_comment='计划结束日期', null=True)),
                ('actual_end_at', models.DateTimeField(blank=True, db_comment='实际完成时间', null=True)),
                ('archived_at', models.DateTimeField(blank=True, db_comment='归档时间', null=True)),
                ('version', models.PositiveIntegerField(db_comment='乐观锁版本', default=1)),
                ('created_by', models.ForeignKey(blank=True, db_comment='创建用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(db_comment='所属组织', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='identity.organization')),
                ('owner', models.ForeignKey(db_comment='项目负责人', on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_comment='最后更新用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project',
                'db_table_comment': '项目',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(db_comment='主键', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_role', models.CharField(choices=[('owner', '负责人'), ('researcher', '研究人员'), ('inspector', '检测人员'), ('viewer', '只读成员')], db_comment='项目成员角色', max_length=24)),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_comment='加入时间')),
                ('created_by', models.ForeignKey(blank=True, db_comment='操作用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(db_comment='所属组织', on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='identity.organization')),
                ('project', models.ForeignKey(db_comment='项目', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(db_comment='成员', on_delete=django.db.models.deletion.PROTECT, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_member',
                'db_table_comment': '项目成员',
            },
        ),
        migrations.CreateModel(
            name='BusinessNumberSequence',
            fields=[
                ('id', models.UUIDField(db_comment='主键', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_type', models.CharField(db_comment='业务类型', max_length=32)),
                ('period_key', models.CharField(db_comment='周期键', max_length=16)),
                ('current_value', models.BigIntegerField(db_comment='当前已分配序号', default=0)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间')),
                ('organization', models.ForeignKey(db_comment='所属组织', on_delete=django.db.models.deletion.CASCADE, related_name='business_number_sequences', to='identity.organization')),
            ],
            options={
                'db_table': 'business_number_sequence',
                'db_table_comment': '业务编号序列',
                'constraints': [models.UniqueConstraint(fields=('organization', 'business_type', 'period_key'), name='uk_business_number_sequence_scope')],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'status', '-updated_at'], name='idx_project_org_status_updated'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'owner', 'status'], name='idx_project_owner_status'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('organization', 'project_no'), name='uk_project_org_project_no'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('planned_end_date__isnull', True), ('planned_start_date__isnull', True), ('planned_end_date__gte', models.F('planned_start_date')), _connector='OR'), name='ck_project_planned_date_order'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['organization', 'user', 'project'], name='idx_project_member_user'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='uk_project_member_project_user'),
        ),
    ]
