# Generated by Django 5.2.16 on 2026-07-24 07:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRequest',
            fields=[
                ('id', models.UUIDField(db_comment='主键', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_comment='所属组织')),
                ('idempotency_key', models.CharField(db_comment='客户端幂等键', max_length=128)),
                ('route_key', models.CharField(db_comment='稳定路由和动作标识', max_length=200)),
                ('request_hash', models.CharField(db_comment='规范化请求摘要', max_length=64)),
                ('status', models.CharField(choices=[('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], db_comment='幂等请求状态', default='processing', max_length=16)),
                ('response_status', models.PositiveSmallIntegerField(db_comment='首次响应状态码', null=True)),
                ('response_body', models.JSONField(db_comment='可安全重放的脱敏响应', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('expires_at', models.DateTimeField(db_comment='过期时间')),
            ],
            options={
                'db_table': 'idempotency_request',
                'db_table_comment': '幂等请求',
            },
        ),
    ]
