# Generated by Django 5.2.16 on 2026-07-24 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencyrequest',
            name='user',
            field=models.ForeignKey(db_comment='请求用户', on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='idempotencyrequest',
            index=models.Index(fields=['expires_at'], name='idx_idempotency_expires'),
        ),
        migrations.AddConstraint(
            model_name='idempotencyrequest',
            constraint=models.UniqueConstraint(fields=('organization_id', 'user', 'route_key', 'idempotency_key'), name='uk_idempotency_request_scope_key'),
        ),
    ]
