# Generated by Django 5.2.16 on 2026-07-24 07:32

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(db_comment='主键', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='最后更新时间')),
                ('organization_code', models.CharField(db_comment='组织代码', max_length=32, unique=True)),
                ('name', models.CharField(db_comment='组织名称', max_length=200)),
                ('status', models.CharField(choices=[('active', '正常'), ('suspended', '停用')], db_comment='组织状态', default='active', max_length=16)),
            ],
            options={
                'db_table': 'organization',
                'db_table_comment': '组织',
                'ordering': ['organization_code'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(db_comment='主键', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_code', models.CharField(db_comment='权限代码', max_length=100, unique=True)),
                ('name', models.CharField(db_comment='权限名称', max_length=100)),
                ('module_code', models.CharField(db_comment='所属模块', max_length=64)),
                ('description', models.CharField(blank=True, db_comment='权限说明', max_length=500)),
            ],
            options={
                'db_table': 'permission',
                'db_table_comment': '权限',
                'ordering': ['module_code', 'permission_code'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(db_comment='主键', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_comment='登录名', max_length=64)),
                ('display_name', models.CharField(db_comment='显示名称', max_length=100)),
                ('email', models.EmailField(blank=True, db_comment='邮箱', max_length=254)),
                ('status', models.CharField(choices=[('active', '正常'), ('locked', '锁定'), ('disabled', '禁用')], db_comment='用户状态', default='active', max_length=16)),
                ('is_super_admin', models.BooleanField(db_comment='平台超级管理员标记', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='最后更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(db_comment='所属组织', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='identity.organization')),
            ],
            options={
                'db_table': 'user_account',
                'db_table_comment': '用户账户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(db_comment='主键', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='最后更新时间')),
                ('role_code', models.CharField(db_comment='稳定角色代码', max_length=64)),
                ('name', models.CharField(db_comment='角色名称', max_length=100)),
                ('description', models.CharField(blank=True, db_comment='角色说明', max_length=500)),
                ('is_system', models.BooleanField(db_comment='是否系统角色', default=False)),
                ('status', models.CharField(choices=[('active', '正常'), ('disabled', '禁用')], db_comment='角色状态', default='active', max_length=16)),
                ('organization', models.ForeignKey(db_comment='所属组织', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='identity.organization')),
            ],
            options={
                'db_table': 'role',
                'db_table_comment': '角色',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(db_comment='主键', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='授权时间')),
                ('created_by', models.ForeignKey(blank=True, db_comment='授权用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_role_permissions', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(db_comment='权限', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='identity.permission')),
                ('role', models.ForeignKey(db_comment='角色', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='identity.role')),
            ],
            options={
                'db_table': 'role_permission',
                'db_table_comment': '角色权限关联',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(db_comment='主键', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='分配时间')),
                ('created_by', models.ForeignKey(blank=True, db_comment='分配用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_roles', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(db_comment='所属组织', on_delete=django.db.models.deletion.CASCADE, related_name='user_role_links', to='identity.organization')),
                ('role', models.ForeignKey(db_comment='角色', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='identity.role')),
                ('user', models.ForeignKey(db_comment='用户', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_role',
                'db_table_comment': '用户角色关联',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'status'], name='idx_user_org_status'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('organization', 'username'), name='uk_user_account_org_username'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('organization', 'email'), name='uk_user_account_org_email'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'role_code'), name='uk_role_org_code'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='uk_role_permission_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='uk_user_role_user_role'),
        ),
    ]
